jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the commit that has been pushed.
      - uses: actions/checkout@v4

      # Setup Hugo, update modules, etc.
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.135.0'
          extended: true

      - name: Update Hugo Modules
        run: hugo mod tidy

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Node Modules
        run: |
          hugo mod npm pack
          npm install

      - name: Build
        run: hugo --minify

      # Debugging steps
      - name: Check Git Status
        run: git status

      - name: List Public Directory
        run: ls -al ./public

      # Push the generated content into the `gh-pages` branch.
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
